name: Release Program

on:
  push:
    tags:
      - '[0-9]\.[0-9]\.[0-9]'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: get-key
        shell: bash
        run: |
          echo "${{ secrets.PFX }}" | base64 --decode > Seonglae.pfx
          echo "${{ secrets.ENV }}" > .env

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install npm dependencies
        shell: bash
        run: yarn

      - name: Run build task
        shell: bash
        run: |
          yarn build
          ln build/Intuiter*.exe Intuiter.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: make artiface
          path: build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: docs/versions/${{ env.RELEASE_VERSION }}.md
          draft: false
          prerelease: false

  publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: seonglae/winget-pkgs

      - name: Set VERSION env
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Make Manifest
        shell: bash
        run: |
          git config --local user.email "sungle3737@gmail.com"
          git config --local user.name "seonglae"
          git remote add microsoft git://github.com/microsoft/winget-pkgs.git
          git pull microsoft master
          cd manifests/s/Seonglae/Intuiter
          mkdir ${{ env.RELEASE_VERSION }}
          cd ${{ env.RELEASE_VERSION }}
          HASH=$(curl -sL https://github.com/seonglae/intuiter/releases/download/${{ env.RELEASE_VERSION }}/Intuiter.exe | sha256sum | cut -c-64)

          echo "PackageIdentifier: Seonglae.Intuiter" >> Seonglae.Intuiter.yaml
          echo "Publisher: Seonglae" >> Seonglae.Intuiter.yaml
          echo "PackageName: Intuiter" >> Seonglae.Intuiter.yaml
          echo "PackageVersion:" ${{ env.RELEASE_VERSION }} >> Seonglae.Intuiter.yaml
          echo "License: MIT" >> Seonglae.Intuiter.yaml
          echo "InstallerType: exe" >> Seonglae.Intuiter.yaml
          echo "InstallerSwitches:" >> Seonglae.Intuiter.yaml
          echo "  Silent: /S" >> Seonglae.Intuiter.yaml
          echo "  SilentWithProgress: /S" >> Seonglae.Intuiter.yaml
          echo "Installers:" >> Seonglae.Intuiter.yaml
          echo "- Architecture: x86" >> Seonglae.Intuiter.yaml
          echo "  InstallerUrl: https://github.com/seonglae/intuiter/releases/download/${{ env.RELEASE_VERSION }}/Intuiter.exe" >> Seonglae.Intuiter.yaml
          echo "  InstallerSha256: `sha256sum build/Intuiter-${{ env.RELEASE_VERSION }}.exe | cut -c1-64`" >> Seonglae.Intuiter.yaml
          echo "ShortDescription: Seonglae.Intuiter" >> Seonglae.Intuiter.yaml
          echo "PackageLocale: en-US" >> Seonglae.Intuiter.yaml
          echo "ManifestType: singleton" >> Seonglae.Intuiter.yaml
          echo "ManifestVersion: 1.0.0" >> Seonglae.Intuiter.yaml

      - name: Commit Manifest
        run: |
          git add .
          git commit -am "Submitting  Intuiter version latest.yaml"

      - name: Create pull request
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_REPOSITORY: microsoft/winget-pkgs
          PULL_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: master
          PULL_REQUEST_BODY: |
            - [o] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
            - [o] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
            - [o] Have you validated your manifest locally with `winget validate --manifest <path>`? 
            - [o] Have you tested your manifest locally with `winge@mast install --manifest <path>`?
            - [o] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?
          PULL_REQUEST_TITLE: Submitting  Intuiter version latest.yaml
