name: Build Artifact

on:
  push:
    branches:
      - develop
      - release

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Github Token
        shell: bash
        run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Get Seonglae Key
        shell: bash
        run: |
          echo "${{ secrets.PFX }}" | base64 --decode > Seonglae.pfx
          echo "${{ secrets.ENV }}" > .env

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install npm dependencies
        run: yarn

      - name: Run build task
        shell: bash
        run: |
          yarn build
          ln build/Intuiter*.exe Intuiter.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: make artiface
          path: build

  test:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/microsoft/winget-pkgs

      - name: Clone window
        shell: bash
        run: |
          cd manifests/s/Seonglae/Intuiter
          mkdir lastest
          cd lastest
          echo "PackageIdentifier: Seonglae.Intuiter" >> Seonglae.Intuiter.yaml
          echo "Publisher: Seonglae" >> Seonglae.Intuiter.yaml
          echo "PackageName: Intuiter" >> Seonglae.Intuiter.yaml
          echo "PackageVersion: lastest >> Seonglae.Intuiter.yaml
          echo "License: MIT" >> Seonglae.Intuiter.yaml
          echo "InstallerType: exe" >> Seonglae.Intuiter.yaml
          echo "InstallerSwitches:" >> Seonglae.Intuiter.yaml
          echo "  Silent: /S" >> Seonglae.Intuiter.yaml
          echo "  SilentWithProgress: /S" >> Seonglae.Intuiter.yaml
          echo "Installers:" >> Seonglae.Intuiter.yaml
          echo "- Architecture: x86" >> Seonglae.Intuiter.yaml
          echo "  InstallerUrl: https://github.com/seonglae/intuiter/releases/lastest/download/Intuiter.exe" >> Seonglae.Intuiter.yaml
          echo "  InstallerSha256: `sha256sum build/Intuiter-0.6.0.exe | cut -c1-64`" >> Seonglae.Intuiter.yaml
          echo "ShortDescription: Seonglae.Intuiter" >> Seonglae.Intuiter.yaml
          echo "PackageLocale: en-US" >> Seonglae.Intuiter.yaml
          echo "ManifestType: singleton" >> Seonglae.Intuiter.yaml
          echo "ManifestVersion: 1.0.0" >> Seonglae.Intuiter.yaml
          winget validate --manifest .
          winget validate --manifest .
